const initialState = {
  header: [
    { id: 1, name: 'آگهی من', order: 1 },
    { id: 2, name: 'همه آگهی ها', order: 1 },
    { id: 3, name: 'همه فروشگاه ها', order: 1 },
    { id: 4, name: 'پشتیبانی', order: 1 },
    { id: 5, name: 'تماس با ما', order: 1 },
    { id: 6, name: 'حساب من', order: 1 },
  ],
  prouducts: [
    {
      id: 1,
      name: 'سرامیک کف ویکتور',
      off: '50',
      rate: '2',
      img: 'http://s5.picofile.com/file/8371493442/1.png',
      price: 20000,
    },
    {
      id: 2,
      name: 'سرامیک کف ویکتور',
      off: '40',
      rate: '3',
      img: 'http://s4.picofile.com/file/8371493450/2.png',
      price: 20000,
    },
    {
      id: 3,
      name: 'سرامیک کف ویکتور',
      off: '30',
      rate: '2.5',
      img: 'http://s3.picofile.com/file/8371493534/3.png',
      price: 200,
    },
    {
      id: 4,
      name: 'سرامیک کف ویکتور',
      off: '20',
      rate: '4',
      img: 'http://s4.picofile.com/file/8371493542/4.png',
      price: 20000,
    },
    {
      id: 5,
      name: 'سرامیک کف ویکتور',
      off: '10',
      rate: '5',
      img: 'http://s5.picofile.com/file/8371493442/1.png',
      price: 20000,
    },
  ],
  sidebar: [
    {
      id: 1,
      name: 'کاشی و سرامیک',
      icon: 'border_vertical',
      link: '',
      color: '#CCB333',
    },
    {
      id: 2,
      name: 'لوازم بهداشتی',
      icon: 'airline_seat_legroom_extras',
      link: '',
      color: '#168D3E',
    },
    {
      id: 3,
      name: 'شیر آلات',
      icon: 'invert_colors',
      link: '',
      color: '#2121B9',
    },
    {
      id: 4,
      name: 'وسیله نقلیه',
      icon: 'drive_eta',
      link: '',
      color: '#808D13',
    },
    {
      id: 5,
      name: 'املاک',
      icon: 'account_balance',
      link: '',
      color: '#C80B45',
    },
    { id: 6, name: 'لوازم شخصی', icon: 'watch', link: '', color: '#23E543' },
    {
      id: 7,
      name: 'لوازم الکترونیکی',
      icon: 'laptop_mac',
      link: '',
      color: '#4D3D08',
    },
    {
      id: 8,
      name: 'موبایل و تبلت',
      icon: 'phone_iphone',
      link: '',
      color: '#1D6CD4',
    },
    { id: 9, name: 'ورزشی', icon: 'rowing', link: '', color: '#EF131A' },
    {
      id: 10,
      name: 'اوقات فراغت',
      icon: 'extension',
      link: '',
      color: '#F1E907',
    },
    { id: 11, name: 'خدمات', icon: 'build', link: '', color: '#4B0E04' },
  ],
  rate: { id: null, value: null },
};
export default initialState;
